- platform: gpio
  pin:
    number: ${button_pin}
    inverted: True
  name: "${upper_devicename} Button"
- platform: gpio
  pin:
    number: ${pir_pin}
  name: "${upper_devicename} PIR Sensor"
  device_class: motion