- platform: gpio
  pin:
    number: ${liquid_level_1_pin}
    inverted: True
    mode: INPUT_PULLUP
  name: "Liquid Level Sensor 1"
  filters:
    - delayed_on_off:
        time_on: ${time_on}
        time_off: ${time_off}
- platform: gpio
  pin:
    number: ${liquid_level_2_pin}
    inverted: True
    mode: INPUT_PULLUP
  name: "Liquid Level Sensor 2"
  filters:
    - delayed_on_off:
        time_on: ${time_on}
        time_off: ${time_off}
- platform: gpio
  pin:
    number: ${liquid_level_3_pin}
    inverted: True
    mode: INPUT_PULLUP
  name: "Liquid Level Sensor 3"
  filters:
    - delayed_on_off:
        time_on: ${time_on}
        time_off: ${time_off}

