- platform: ld2410
  has_target:
    name: Presence
  has_moving_target:
    name: "Moving Target"
  has_still_target:
    name: "Still Target"
  out_pin_presence_status:
    name: "Out Pin Presence Status"
