substitutions:
  devicename: ah01_rly4
  upper_devicename: AH01_RLY4

esphome: !include adafruit_huzzah/device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger: !include base/logger.yaml
# Enable Home Assistant API
#api:
ota:
# Enable remote restart from HA
switch: !include adafruit_huzzah/switch.yaml
# Set of four relays on GPIO
switch: !include relay/gpio_4_relay.yaml
# Blue LED (either output+light or status_led, not both)
output: !include adafruit_huzzah/output.yaml
light: !include adafruit_huzzah/light.yaml
#status_led: !include adafruit_huzzah/status_led.yaml
# Flash Button
binary_sensor: !include adafruit_huzzah/binary_sensor.yaml
