substitutions:
  devicename: ah01_t4
  upper_devicename: AH01_T4

esphomeyaml: !include adafruit_huzzah/device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger:
  level: DEBUG
# Enable Home Assistant API
#api: (broken with MQTT for now)
ota:
# Need Dallas for one wire sensors
dallas: !include sensor/dallas.yaml
# Set of four DS18B20 Temperature probes
sensor: !include sensor/ds18b20x4.yaml
# Blue LED (either output+light or status_led, not both)
output: !include adafruit_huzzah/output.yaml
light: !include adafruit_huzzah/light.yaml
#status_led: !include adafruit_huzzah/status_led.yaml
# Flash Button
binary_sensor: !include adafruit_huzzah/binary_sensor.yaml
