substitutions:
  devicename: ah01_tph
  upper_devicename: AH01_TPH

esphomeyaml: !include adafruit_huzzah/device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger:
# Enable Home Assistant API
#api: (broken with MQTT for now)
ota:
# Need I2C bus for sensors (defaults are good)
i2c:
# BME280 Temperature, Pressure and Humidity
sensor: !include sensor/bme280.yaml
# Red and Blue LEDs
output: !include adafruit_huzzah/output.yaml
light: !include adafruit_huzzah/light.yaml
# Flash Button
binary_sensor: !include adafruit_huzzah/binary_sensor.yaml
