substitutions:
  devicename: ah03_th
  upper_devicename: AH03_TH

esphomeyaml: !include adafruit_huzzah/device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger: !include base/logger.yaml
# Enable Home Assistant API
#api: (broken with MQTT for now)
ota:
# Need I2C bus for sensors
i2c: !include connection/i2c.yaml
# SHT31-D Temperature and Humidity
sensor: !include sensor/sht3x_d.yaml
# Blue LED (either output+light or status_led, not both)
output: !include adafruit_huzzah/output.yaml
light: !include adafruit_huzzah/light.yaml
#status_led: !include adafruit_huzzah/status_led.yaml
# Flash Button
binary_sensor: !include adafruit_huzzah/binary_sensor.yaml
