substitutions:
  devicename: dm01_sv1
  upper_devicename: DM01_SV1
  tilt_closed_value: "5"
  tilt_opened_value: "60"
  device_class: shutter

esphome: !include d1mini/mqtt_discovery_device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger: !include base/logger.yaml
# Expose some info to HA
text_sensor: !include base/text_sensor.yaml
# Enable Home Assistant API
#api: (broken with MQTT for now)
ota:
# Enable remote restart from HA
switch: !include d1mini/switch.yaml
#binary_sensor: !include nodemcu/binary_sensor.yaml
# Blue LED (either output+light or status_led, not both)
cover: !include d1mini/template_tilt_cover.yaml
sensor: !include sensor/adc_cover_position.yaml
globals: !include d1mini/globals.yaml
#sensor: !include nodemcu/mqtt_cover_with_input_sensor.yaml
output: !include d1mini/cover_servo_output.yaml
light: !include d1mini/light.yaml
#status_led: !include nodemcu/status_led.yaml
servo: !include d1mini/mg90_cover_servo.yaml

