substitutions:
  devicename: dm06_svreb1
  upper_devicename: DM06_SVREB1
  tilt_closed_value: "5"
  tilt_opened_value: "60"
  tilt_invert_state: "false"
  open_above_tilt: "5"
  device_class: shutter
  led_pin: D4
  servo_pin: D5
  loop_delay_ms: "0"
  final_delay_ms: "800"
  button_pin: D1
  encoder_pin_a: D6
  encoder_pin_b: D7
  encoder_min_value: "0"
  encoder_max_value: "100"

esphome: !include d1mini/mqtt_discovery_device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger: !include logger/debug.yaml
# Expose some info to HA
text_sensor: !include text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
switch: !include switch/restart.yaml
cover: !include cover/template_tilt_rotary_encoder.yaml
#sensor: !include cover/adc_cover_position_sensor.yaml
globals: !include globals/cover.yaml
output: !include output/blue_led_servo.yaml
light: !include light/blue_led.yaml
servo: !include servo/mg90_cover.yaml
# Rotary encoder with button
binary_sensor: !include binary_sensor/button.yaml
sensor: !include sensor/rotary_encoder_cover_position.yaml

