substitutions:
  devicename: nm03_sv1
  upper_devicename: NM03_SV1

esphome: !include nodemcu/dev_device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger: !include base/logger.yaml
# Enable Home Assistant API
#api: (broken with MQTT for now)
ota:
binary_sensor: !include nodemcu/binary_sensor.yaml
#switch: !include nodemcu/switch.yaml
# Blue LED (either output+light or status_led, not both)
cover: !include nodemcu/cover.yaml
sensor: !include sensor/adc_cover_position.yaml
#sensor: !include nodemcu/sensor.yaml
output: !include nodemcu/output.yaml
light: !include nodemcu/light.yaml
#status_led: !include nodemcu/status_led.yaml

