substitutions:
  devicename: nm04_sv1
  upper_devicename: NM04_SV1
  tilt_closed_value: "95"
  tilt_opened_value: "40"
  tilt_min: "100"
  tilt_max: "0"
  open_above_tilt: "5"
  device_class: shutter
  button_pin: D2
  led_pin: D4
  servo_pin: D5
  loop_delay_ms: "100"
  final_delay_ms: "100"

esphome: !include nodemcu/mqtt_discovery_device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger: !include logger/debug.yaml
# Expose some info to HA
text_sensor: !include text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
switch: !include switch/restart.yaml
light: !include light/blue_led.yaml
binary_sensor: !include binary_sensor/button.yaml
# Cover
globals: !include globals/cover.yaml
cover: !include cover/template_tilt.yaml
sensor: !include sensor/adc_temt6000.yaml
servo: !include servo/mg995_cover.yaml
output:
  - <<: !include output/blue_led.yaml
  - <<: !include output/servo.yaml

