substitutions:
  devicename: nm06_rfx1
  upper_devicename: NM06_RFX1

esphome: !include nodemcu/device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger: !include base/logger.yaml
# Enable Home Assistant API
#api: (broken with MQTT for now)
ota:
# Enable remote restart from HA
switch: !include nodemcu/switch.yaml
binary_sensor: !include nodemcu/rf_remote_binary_sensor.yaml
# Blue LED (either output+light or status_led, not both)
output: !include nodemcu/output.yaml
light: !include nodemcu/light.yaml
#status_led: !include nodemcu/status_led.yaml
remote_receiver: !include nodemcu/remote_receiver.yaml
#remote_transmitter: !include nodemcu/remote_transmitter.yaml
