substitutions:
  devicename: nm07_rfx1
  upper_devicename: NM07_RFX1
  button_pin: D2
  led_pin: D4
  rf_transmit_pin: D2

esphome: !include nodemcu/device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger: !include logger/debug.yaml
# Expose some info to HA
text_sensor: !include text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
switch: !include switch/restart_rc_switch.yaml
binary_sensor: !include binary_sensor/button.yaml
output: !include output/blue_led.yaml
light: !include light/blue_led.yaml
remote_transmitter: !include remote_transmitter/rc_switch.yaml
