substitutions:
  devicename: nm08_sv1
  upper_devicename: NM08_SV1
  button_pin: D2
  led_pin: D4
  servo_pin: D5
  
esphome: !include nodemcu/device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger: !include logger/debug.yaml
# Expose some info to HA
text_sensor: !include text_sensor/wifi_info.yaml
# Enable Home Assistant API
#api: (broken with MQTT for now)
ota:
# Enable remote restart from HA
switch:
  - <<: !include switch/restart.yaml
  - <<: !include switch/servo.yaml
light: !include light/blue_led.yaml
binary_sensor: !include binary_sensor/button.yaml
servo: !include servo/mg995_switch.yaml
output:
  - <<: !include output/blue_led.yaml
  - <<: !include output/servo.yaml

