substitutions:
  devicename: nm16_th
  upper_devicename: NM16_TH

esphome: !include nodemcu/device.yaml
wifi: !include connection/wifi_ap.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger: !include base/logger.yaml
# Expose some info to HA
text_sensor: !include base/text_sensor.yaml
# Enable Home Assistant API
#api: (broken with MQTT for now)
ota:
# Enable remote restart from HA
switch: !include nodemcu/switch.yaml
binary_sensor: !include nodemcu/binary_sensor.yaml
light: !include nodemcu/light.yaml
output: !include nodemcu/output.yaml
#status_led: !include nodemcu/status_led.yaml
# DHT22 Temperature and Humidity
sensor: !include sensor/dht22.yaml
# Web Server
web_server: !include connection/web_server.yaml
captive_portal:
