substitutions:
  devicename: sb01
  upper_devicename: SB01

esphomeyaml: !include sonoff_basic/device.yaml
wifi: !include connection/wifi.yaml
mqtt: !include connection/mqtt.yaml
# Enable logging
logger:
# Enable Home Assistant API
#api: (broken with MQTT for now)
ota:
binary_sensor: !include sonoff_basic/binary_sensor.yaml
switch: !include sonoff_basic/switch.yaml
output: !include sonoff_basic/output.yaml
light: !include sonoff_basic/light.yaml

