substitutions:
  devicename: cyd01
  upper_devicename: CYD01
  device_friendly_name: "CYD01 Cheap Yellow Display ESP32-2432S028R"
  red_led_pin: "GPIO4"
  red_led_inverted: "true"
  green_led_pin: "GPIO16"
  green_led_inverted: "true"
  blue_led_pin: "GPIO17"
  blue_led_inverted: "true"
  tft_clk_pin: "GPIO14"
  tft_mosi_pin: "GPIO13"
  tft_miso_pin: "GPIO12"
  touch_clk_pin: "GPIO25"
  touch_mosi_pin: "GPIO32"
  touch_miso_pin: "GPIO39"
  backlight_id: "backlight"
  backlight_switch_id: "backlight_switch"
  buffer_size: "25%"
  home_page_id: "engine_sensors_page"
  beeper_cancel_id: "beeper_cancel"
  beeper_pin: "GPIO26"
  beeper_id: "beeper"
  beeper_frequency: "1000Hz"
  beeper_level: "50%"
  beeper_switch_id: "beeper_switch"
  header_text_color: "0xFFFFFF"
  footer_text_color: "0xFFFFFF"
  dark_switch_id: "dark_switch"
  dark_text_color: "0xFFFFFF"
  dark_drop_value_bg_color: "0x202020"
  dark_sensor_bg_color: "0x000000"
  dark_level_page_bg_color: "0x000000"
  dark_engine_sensors_page_bg_color: "0xFFFFFF"
  light_text_color: "0x000000"
  light_drop_value_bg_color: "0xD0D0D0"
  light_sensor_bg_color: "0xFFFFFF"
  light_level_page_bg_color: "0xFFFFFF"
  light_engine_sensors_page_bg_color: "0x000000"
  engine_oil_pres_green_kpa: "172.375" # 25 psi
  engine_oil_pres_yellow_kpa: "103.425" # 15 psi
  engine_oil_temp_green_C: "90" # 194 F
  engine_oil_temp_yellow_C: "115" # 239 F
  engine_oil_temp_red_C: "145" # 293 F
  engine_coolant_temp_green_C: "95" # 203 F
  engine_coolant_temp_yellow_C: "105" # 221 F
  engine_coolant_temp_red_C: "113" # 235.4 F
  trans_temperature_green_C: "70" # 158 F
  trans_temperature_yellow_C: "88" # 190.4 F
  trans_temperature_red_C: "100" # 212 F
  control_module_voltage_yellow_low_V: "13.75"
  control_module_voltage_red_low_V: "12.25"
  control_module_voltage_red_high_V: "14.75"
  
esphome: !include ../base/device_friendly_name.yaml
esp32: !include ../esp32/esp32dev_idf.yaml
wifi: !include ../connection/wifi_caravan.yaml
mqtt: !include ../connection/mqtt_caravan.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor:
  - <<: !include ../text_sensor/wifi_info.yaml
ota: !include ../ota/esphome.yaml
# Enable remote restart from HA
button: 
  - <<: !include ../button/restart.yaml
  - <<: !include ../button/shutdown.yaml
  - <<: !include ../button/safe_mode.yaml
light:
  - <<: !include ../light/backlight_lvgl.yaml
  - <<: !include ../light/rgb.yaml
# Setup SPI for the display. The ESP32-2432S028R uses separate SPI buses for display and touch
spi:
  - <<: !include ../connection/spi_tft.yaml
  - <<: !include ../connection/spi_touch.yaml
output:
  - <<: !include ../output/backlight_ledc.yaml
  - <<: !include ../output/red_ledc.yaml
  - <<: !include ../output/green_ledc.yaml
  - <<: !include ../output/blue_ledc.yaml
  - <<: !include ../output/beeper_ledc.yaml
switch:
  - <<: !include ../switch/beeper_lvgl.yaml
  - <<: !include ../switch/dark_lvgl.yaml
sensor:
  - <<: !include ../sensor/cyd_board_ldr.yaml
  - <<: !include ../sensor/mqtt_wican_engine_coolant_temp_lvgl.yaml
#  - <<: !include ../sensor/mqtt_wican_intake_air_temperature_lvgl.yaml
  - <<: !include ../sensor/mqtt_wican_trans_temperature_lvgl.yaml
  - <<: !include ../sensor/mqtt_wican_engine_oil_pres_lvgl.yaml
  - <<: !include ../sensor/mqtt_wican_engine_oil_temp_lvgl.yaml
  - <<: !include ../sensor/mqtt_wican_calc_engine_load_lvgl.yaml
#  - <<: !include ../sensor/mqtt_wican_cmdthrottle_actuator_lvgl.yaml
  - <<: !include ../sensor/mqtt_wican_control_module_volt_lvgl.yaml
  - <<: !include ../sensor/mqtt_dm18mpu_level_sensor_roll_trimmed_lvgl.yaml
  - <<: !include ../sensor/mqtt_dm18mpu_level_sensor_pitch_trimmed_lvgl.yaml
  - <<: !include ../sensor/mqtt_dm18mpu_level_sensor_left_front_drop_lvgl.yaml
  - <<: !include ../sensor/mqtt_dm18mpu_level_sensor_left_rear_drop_lvgl.yaml
  - <<: !include ../sensor/mqtt_dm18mpu_level_sensor_right_front_drop_lvgl.yaml
  - <<: !include ../sensor/mqtt_dm18mpu_level_sensor_right_rear_drop_lvgl.yaml
image:
  - <<: !include ../image/rear_view.yaml
  - <<: !include ../image/right_side_view.yaml
font:
  - <<: !include ../font/montserrat_bold_22.yaml
  - <<: !include ../font/montserrat_bold_24.yaml
  - <<: !include ../font/montserrat_bold_26.yaml
  - <<: !include ../font/montserrat_bold_28.yaml
  - <<: !include ../font/montserrat_bold_30.yaml
  - <<: !include ../font/montserrat_bold_32.yaml
  - <<: !include ../font/montserrat_bold_34.yaml
  - <<: !include ../font/montserrat_bold_36.yaml
  - <<: !include ../font/montserrat_bold_38.yaml
  - <<: !include ../font/montserrat_bold_40.yaml
lvgl:
    <<: !include ../lvgl/buffer_size.yaml
    <<: !include ../lvgl/disp_bg_color.yaml
    <<: !include ../lvgl/style_definitions.yaml
    <<: !include ../lvgl/button_header_nav_footer.yaml
    pages:
      - <<: !include ../lvgl/engine_sensors_page.yaml
      - <<: !include ../lvgl/level_page.yaml
# Setup the ili9xxx platform
display:
  - <<: !include ../display/ili9342_lvgl.yaml
# Set up the xpt2046 touch platform
touchscreen:
  - <<: !include ../touchscreen/xpt2046.yaml

