substitutions:
  devicename: dm18mpu
  upper_devicename: DM18MPU
  led_pin: D4
  update_interval: "500ms"
  window_size: "10"
  send_every: "5"

esphome: !include ../base/name_onboot.yaml
esp8266: !include ../esp8266/d1mini_restore.yaml
wifi: !include ../connection/wifi_caravan.yaml
mqtt: !include ../connection/mqtt_caravan.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_led.yaml
# Need I2C bus for sensors
i2c: !include ../connection/i2c.yaml
# MPU6050 sensor for acceleration and gyro
sensor: !include ../sensor/mpu6050_pitch_roll.yaml

