substitutions:
  devicename: dm20br
  upper_devicename: DM20BR
  blue_led_pin: GPIO2 # D4
  binary_pin: GPIO5 # D1
  relay_pin: GPIO4 # D2
  binary_sensor_name: "Water Pump Signal"
  relay_name: "Water Pump Toggle"
  relay_duration: "1s"

esphome: !include ../base/name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi_caravan.yaml
mqtt: !include ../connection/mqtt_caravan.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button:
  - <<: !include ../button/restart.yaml
  - <<: !include ../button/relay.yaml
light: !include ../light/blue_led.yaml
output:
  - <<: !include ../output/blue_led.yaml
  - <<: !include ../output/relay.yaml
# Binary input for water pump signal
binary_sensor: !include ../binary_sensor/signal.yaml
