substitutions:
  devicename: dm22ina
  upper_devicename: DM22INA
  blue_led_pin: GPIO2
  shunt_resistance: "0.00075 ohm"
  max_voltage: "32.0V"
  max_current: "100A"
  update_interval: "60s"
  
esphome: !include ../base/name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi_caravan.yaml
mqtt: !include ../connection/mqtt_caravan.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor:
  - <<: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_led.yaml
# Enable I2C for the INA219 device
i2c:
# INA219 on default pins
sensor: !include ../sensor/ina219.yaml
