substitutions:
  devicename: dm24jbd
  upper_devicename: DM24JBD
  device_friendly_name: "DM24JBD BMS GJ-12V100AH-0526-161"
  blue_led_pin: GPIO2
  update_interval: "4s"
  external_components_source: github://syssi/esphome-jbd-bms@main
  #bms0_mac_address: "A4:C1:37:40:2F:C8"
  #bms0_name: "GJ-12V100AH-0526-048"
  bms0_mac_address: "70:3E:97:07:F9:F6"
  bms0_name: "GJ-12V100AH-0526-161"
  # Change to ALWAYS_OFF if defining multiple BMS connections on one ESP
  #  or use as backup for HA based BMS addon
  restore_mode: "ALWAYS_OFF"
  
esphome: !include ../base/device_friendly_name_onboot.yaml
external_components: !include ../external_components/generic.yaml
esp32: !include ../esp32/wemos_d1_mini32.yaml
wifi: !include ../connection/wifi_caravan.yaml
mqtt: !include ../connection/mqtt_caravan.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor:
  - <<: !include ../text_sensor/wifi_info.yaml
  - <<: !include ../text_sensor/bms0_jbd_bms_ble.yaml
ota: !include ../ota/esphome.yaml
# Enable remote restart from HA
button: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_ledc.yaml
# JBD BMS BLE Setup
esp32_ble_tracker: !include ../bluetooth/jbd_bms.yaml
ble_client: !include ../connection/bms0_ble_client0.yaml
jbd_bms_ble: !include ../jbd_bms_ble/bms0_client0.yaml
binary_sensor: !include ../binary_sensor/bms0_jbd_bms_ble.yaml
sensor:
  - <<: !include ../sensor/bms0_jbd_bms_ble.yaml
  - <<: !include ../sensor/bms0_ble_rssi.yaml
  - <<: !include ../sensor/esp32_internal_temperature.yaml
switch:
  - <<: !include ../switch/client0_ble_client.yaml
  - <<: !include ../switch/bms0_jbd_bms_ble.yaml
