substitutions:
  devicename: dm25brwm
  upper_devicename: DM25BRWM
  device_friendly_name: "DM25BRWM Water Pump"
  blue_led_pin: GPIO2 # D4
  flow_meter_pin: GPIO14 # D5
  binary_pin: GPIO5 # D1
  relay_pin: GPIO4 # D2
  binary_sensor_name: "Signal"
  relay_name: "Toggle"
  relay_duration: "1s"
  update_interval: "5s"
  gallons_per_pulse: "0.0005336"
  flow_accuracy: "2"
  total_accuracy: "1"
  offset: "-0.148"
  multiplier: "104.17"
  window_size: "12"
  send_every: "3"
  pressure_accuracy: "1"
  
esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/d1mini_restore.yaml
wifi: !include ../connection/wifi_caravan.yaml
mqtt: !include ../connection/mqtt_caravan.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota: !include ../ota/esphome.yaml
# Persist calibration of pressure
globals: !include ../globals/pressure_offset.yaml
# Enable remote restart from HA
button:
  - <<: !include ../button/restart.yaml
  - <<: !include ../button/flow_pulse_counter_reset.yaml
  - <<: !include ../button/relay.yaml
  - <<: !include ../button/set_pressure_offset.yaml
light: !include ../light/blue_led.yaml
output:
  - <<: !include ../output/blue_led.yaml
  - <<: !include ../output/relay.yaml
# Binary input for water pump signal
binary_sensor: !include ../binary_sensor/signal.yaml
# Pulse counter for water flow sensor
sensor:
  - <<: !include ../sensor/water_flow_pulse_count.yaml
  - <<: !include ../sensor/adc_pressure_sensor_filtered_offset.yaml

