substitutions:
  devicename: dm29br4
  upper_devicename: DM29BR4
  device_friendly_name: "DM29BR4 Binary and Four Relays"
  blue_led_pin: D4
  binary_pin: D1
  binary_sensor_name: "Signal"

esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi_caravan.yaml
mqtt: !include ../connection/mqtt_caravan.yaml
# Enable web server
web_server:
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota: !include ../ota/esphome.yaml
# Enable remote restart from HA
button:
  - <<: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
output:
  - <<: !include ../output/blue_led.yaml
binary_sensor: !include ../binary_sensor/signal.yaml
# Set of four relays on GPIO
switch:
  - <<: !include ../switch/gpio_relay_1.yaml
  - <<: !include ../switch/gpio_relay_2.yaml
  - <<: !include ../switch/gpio_relay_3.yaml
  - <<: !include ../switch/gpio_relay_4_D2.yaml

