substitutions:
  devicename: dm02sv1
  upper_devicename: DM02SV1
  device_friendly_name: "DM02SV1 Blinds"
  cover_name: right_pull
  tilt_closed_value: "95"
  tilt_opened_value: "40"
  tilt_min: "100"
  tilt_max: "0"
  open_above_tilt: "5"
  device_class: blind
  blue_led_pin: D4
  servo_pin: D5
  transition_length: 0s
  auto_detach_time: 100ms

esphome: !include ../base/device_friendly_name_mqtt_discovery.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
# Cover
globals: !include ../globals/cover.yaml
cover: !include ../cover/template_tilt.yaml
sensor: 
  - <<: !include ../sensor/adc_temt6000.yaml
  - <<: !include ../sensor/wifi_signal.yaml
servo: !include ../servo/mg90_cover.yaml
output:
  - <<: !include ../output/blue_led.yaml
  - <<: !include ../output/servo.yaml

