substitutions:
  devicename: dm09qmc1
  upper_devicename: DM09QMC1
  device_friendly_name: "DM09QMC1 Water Meter"
  blue_led_pin: D4
  gal_per_pulse: "0.0085"
  update_interval: "40ms"
  oversampling: "64x"
  delta: "5.0"
  output_update_interval_sec: "5.0"
  output_delta: "0.01"
  x_throttle: "60s"
  
esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug_info_qmc5883l.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota: !include ../ota/esphome.yaml
# Enable remote restart from HA
button: !include ../button/restart.yaml
output: !include ../output/blue_led.yaml
light: !include ../light/blue_led.yaml
# Need I2C bus for sensors
i2c: !include ../connection/i2c.yaml
globals: !include ../globals/water.yaml
interval: !include ../interval/compute_water.yaml
sensor:
  - <<: !include ../sensor/qmc5883l_z.yaml
  - <<: !include ../sensor/pulse_count_water.yaml
  - <<: !include ../sensor/pulse_count_water_total.yaml
