substitutions:
  devicename: dm09qmc1
  upper_devicename: DM09QMC1
  led_pin: D4
  
esphome: !include ../d1mini/device.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button: !include ../button/restart.yaml
output: !include ../output/blue_led.yaml
light: !include ../light/blue_led.yaml
# Need I2C bus for sensors
i2c: !include ../connection/i2c.yaml
sensor: !include ../sensor/qmc5883l.yaml
