substitutions:
  devicename: dm10tr1
  upper_devicename: DM10TR1
  device_friendly_name: "DM10TR1 Hot Water Recirc"
  blue_led_pin: D4
  one_wire_pin: D6
  probe_number: "1"
  relay_number: "1"
  relay_pin: D5
  probe_addr: "0xED01204BF4F92028"
  update_interval: "5s"

esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota: !include ../ota/esphome.yaml
# Enable remote restart from HA
button: 
  - <<: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_led.yaml
# Need for one wire sensors
one_wire: !include ../sensor/one_wire.yaml
# Single relay to run the pump and valve
switch:
  - <<: !include ../switch/gpio_relay.yaml
# Single DS18B20 Temperature probe
sensor: !include ../sensor/ds18b20x1.yaml
# Bang Bang Control for hot water recirc
climate: !include ../climate/bang_bang_hot_water_recirc.yaml

