substitutions:
  devicename: dm17sht
  upper_devicename: DM17SHT
  device_friendly_name: "DM17SHT Climate"
  blue_led_pin: D4
  id_temperature_sensor: "sht4x_temperature_sensor"
  id_humidity_sensor: "sht4x_humidity_sensor"

esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota: !include ../ota/esphome.yaml
# Enable remote restart from HA
button: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_led.yaml
# SHT4X Temperature and Humidity
# Requires I2C
i2c:
sensor: !include ../sensor/sht4x.yaml

