substitutions:
  devicename: dm20ps1
  upper_devicename: DM20PS1
  led_pin: D4
  sensor_pin: D3

esphome: !include ../base/name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button: 
  - <<: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_led.yaml
# Binary GPIO sensor
binary_sensor: !include ../binary_sensor/proximity.yaml
