substitutions:
  devicename: dm28rsht
  upper_devicename: DM28RSHT
  device_friendly_name: "DM28RSHT Relay and Climate"
  blue_led_pin: D4
  relay_pin: D1
  relay_name: "Power Cycle"
  relay_duration: "5s"

esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi_lakefront.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable web server
web_server:
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button:
  - <<: !include ../button/restart.yaml
  - <<: !include ../button/relay.yaml
light: !include ../light/blue_led.yaml
output:
  - <<: !include ../output/blue_led.yaml
  - <<: !include ../output/relay.yaml
# SHT4X Temperature and Humidity
# Requires I2C
i2c:
sensor: !include ../sensor/sht4x.yaml

