substitutions:
  devicename: dm30aqth
  upper_devicename: DM30AQTH
  device_friendly_name: "DM30AQTH Air Quality and Climate"
  blue_led_pin: GPIO2 # D4
  update_interval: "60s"
  eco2_accuracy_decimals: "1"
  tvoc_accuracy_decimals: "1"
  id_temperature_sensor: "sht4x_temperature_sensor"
  id_humidity_sensor: "sht4x_humidity_sensor"
  reset_duration: "1s"
  reset_pin: GPIO12 # D6
  set_switch_pin: GPIO14 # D5

esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable web server
web_server:
# Enable logging
logger: !include ../logger/debug_no_uart.yaml
# Expose some info to HA
text_sensor:
  - <<: !include ../text_sensor/wifi_info.yaml
ota: !include ../ota/esphome.yaml
# I2C needed for AHT21 and ENS160
i2c: !include ../connection/i2c.yaml
# UART needed for PMS7003
uart: !include ../uart/default_9600baud.yaml
# Enable remote restart from HA
button:
  - <<: !include ../button/restart.yaml
  - <<: !include ../button/reset.yaml
switch:
  - <<: !include ../switch/set_switch.yaml
light: !include ../light/blue_led.yaml
output:
  - <<: !include ../output/blue_led.yaml
  - <<: !include ../output/reset.yaml
# DHT22 Temperature and Humidity
sensor:
  - <<: !include ../sensor/sht4x.yaml
  - <<: !include ../sensor/sgp30.yaml
  - <<: !include ../sensor/pmsx003.yaml

