substitutions:
  devicename: dm31ld
  upper_devicename: DM31LD
  device_friendly_name: "DM31LD Presence"
  blue_led_pin: D4
  sensor_pin: D2

esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug_no_uart.yaml
# Expose some info to HA
text_sensor:
  - <<: !include ../text_sensor/wifi_info.yaml
  - <<: !include ../text_sensor/ld2410.yaml
ota:
  - platform: esphome
# Enable remote restart from HA
button:
  - <<: !include ../button/restart.yaml
  - <<: !include ../button/ld2410.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_led.yaml
# UART Required for LD2410B
uart:
  - <<: !include ../uart/default_256000baud.yaml
# LD2410B Radar Human Presence Detector
ld2410:
binary_sensor:
  - <<: !include ../binary_sensor/ld2410.yaml
  - <<: !include ../binary_sensor/proximity_no_invert.yaml
number:
  - <<: !include ../number/ld2410.yaml
#select:
#  - <<: !include ../select/ld2410.yaml
sensor:
  - <<: !include ../sensor/ld2410.yaml
switch:
  - <<: !include ../switch/ld2410.yaml
