substitutions:
  devicename: gw01
  upper_devicename: GW01
  button_pin: GPIO4
  blue_led_pin: GPIO13
  red_led_pin: GPIO12
  relay_pin: GPIO14

esphome: !include ../base/name_onboot.yaml
esp8266: !include ../esp8266/esp01_1m.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
binary_sensor: !include ../binary_sensor/button_toggle_relay.yaml
switch: !include ../switch/relay_restore_default_on.yaml
button: !include ../button/restart.yaml
output:
  - <<: !include ../output/blue_led.yaml
  - <<: !include ../output/red_led.yaml
light:
  - <<: !include ../light/blue_led.yaml
  - <<: !include ../light/red_led.yaml

