substitutions:
  devicename: nm08sv1
  upper_devicename: NM08SV1
  device_friendly_name: "NM08SV1 Lock Servo"
  button_pin: D3
  blue_led_pin: D4
  servo_pin: D5
  on_level: 70%
  off_level: 0%
  transition_length: 0s
  auto_detach_time: 0s
  
esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/nodemcuv2.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
# Enable Home Assistant API
#api: (broken with MQTT for now)
ota: !include ../ota/esphome.yaml
# Enable remote restart from HA
button:
  - <<: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
binary_sensor: !include ../binary_sensor/button.yaml
servo: !include ../servo/mg995_lock.yaml
lock:
  - <<: !include ../lock/servo.yaml
output:
  - <<: !include ../output/blue_led.yaml
  - <<: !include ../output/servo.yaml

