substitutions:
  devicename: nm10tph
  upper_devicename: NM10TPH
  device_friendly_name: "NM10TPH Climate"
  button_pin: D3
  blue_led_pin: D4
  temp_offset: "0.0"

esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/nodemcuv2.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota: !include ../ota/esphome.yaml
# Enable remote restart from HA
button: !include ../button/restart.yaml
binary_sensor: !include ../binary_sensor/button.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_led.yaml
# Need I2C bus for sensors
i2c: !include ../connection/i2c.yaml
# BME280 Temperature, Pressure and Humidity
sensor: !include ../sensor/bme280_i2c.yaml

