substitutions:
  devicename: nm14rly4
  upper_devicename: NM14RLY4
  device_friendly_name: "NM14RLY4 Relays"
  button_pin: D3
  blue_led_pin: D4

esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/nodemcuv2.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button:
  - <<: !include ../button/restart.yaml
# Set of four relays on GPIO
switch:
  - <<: !include ../switch/gpio_relay_1.yaml
  - <<: !include ../switch/gpio_relay_2.yaml
  - <<: !include ../switch/gpio_relay_3.yaml
  - <<: !include ../switch/gpio_relay_4.yaml
binary_sensor: !include ../binary_sensor/button.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_led.yaml
