substitutions:
  devicename: sb07
  upper_devicename: SB07
  button_pin: GPIO0
  led_pin: GPIO13
  relay_pin: GPIO12

esphome: !include ../sonoff_basic/device.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
binary_sensor: !include ../binary_sensor/button_toggle_relay.yaml
switch: !include ../switch/relay.yaml
button: !include ../button/restart.yaml
output: !include ../output/green_led.yaml
light: !include ../light/green_led.yaml

