- platform: sonoff_d1
  use_rm433_remote: False
  min_value: ${min_value}
  max_value: ${max_value}
  name: ${upper_devicename}
  id: dimmer
  restore_mode: RESTORE_DEFAULT_OFF
  gamma_correct: ${gamma_correct}
  default_transition_length: 1s
