- platform: restart
  name: "${upper_devicename} Restart"
- platform: gpio
  name: "${devicename}_1"
  restore_mode: RESTORE_DEFAULT_OFF
  pin:
    number: D5
    inverted: yes
- platform: gpio
  name: "${devicename}_2"
  restore_mode: RESTORE_DEFAULT_OFF
  pin:
    number: D6
    inverted: yes
- platform: gpio
  name: "${devicename}_3"
  restore_mode: RESTORE_DEFAULT_OFF
  pin:
    number: D7
    inverted: yes
- platform: gpio
  name: "${devicename}_4"
  restore_mode: RESTORE_DEFAULT_OFF
  pin:
    number: D8
    inverted: yes

