- platform: template
  name: "Latch Servo"
  id: latch_servo_switch
  optimistic: true
  turn_on_action:
    - servo.write:
        id: switch_servo
        level: ${on_level}
  turn_off_action:
    - servo.write:
        id: switch_servo
        level: ${off_level}
