substitutions:
  devicename: dm06reb1
  upper_devicename: DM06REB1
  blue_led_pin: D4
  button_pin: D1
  encoder_pin_a: D6
  encoder_pin_b: D7
  encoder_min_value: "0"
  encoder_max_value: "100"
  set_rotary_encoder_topic: "${devicename}/sensor/${devicename}_set_rotary_encoder/command"
  
esphome: !include ../base/name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button: !include ../button/restart.yaml
output: !include ../output/blue_led.yaml
light: !include ../light/blue_led.yaml
# Rotary encoder with button
binary_sensor: !include ../binary_sensor/button.yaml
sensor: !include ../sensor/rotary_encoder_settable.yaml

