substitutions:
  devicename: dm21pres
  upper_devicename: DM21PRES
  led_pin: D4
  update_interval: "1.0s"
  offset: 0.0
  multiplier: 80.0

esphome: !include ../base/name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button: 
  - <<: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_led.yaml
# Analog pressure sensor
sensor: !include ../sensor/adc_pressure_sensor.yaml