substitutions:
  devicename: dm22ll1
  upper_devicename: DM22ll1
  blue_led_pin: D4
  sensor_pin: D1
  
esphome: !include ../base/name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button: 
  - <<: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_led.yaml
# Liquid level sensor on GPIO
binary_sensor: !include ../binary_sensor/d1cs-d_liquid_level.yaml