substitutions:
  devicename: dm25wm
  upper_devicename: DM25WM
  device_friendly_name: "DM25WM Water Meter"
  blue_led_pin: GPIO2 # D4
  flow_meter_pin: GPIO14 # D5
  update_interval: "5s"
  updates_per_minute: "12"
  gallons_per_pulse: "0.00841"
  flow_accuracy: "2"
  total_accuracy: "1"
  offset: "-0.1533"
  multiplier: "125"
  window_size: "30"
  send_every: "5"
  pressure_accuracy: "1"
  
esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi_caravan.yaml
mqtt: !include ../connection/mqtt_caravan.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button:
  - <<: !include ../button/restart.yaml
  - <<: !include ../button/flow_pulse_counter_reset.yaml
light: !include ../light/blue_led.yaml
output:
  - <<: !include ../output/blue_led.yaml
# Pulse counter for water flow sensor
sensor:
  - <<: !include ../sensor/water_flow_pulse_count.yaml
  - <<: !include ../sensor/adc_pressure_sensor_filtered.yaml

