substitutions:
  devicename: nm20ac1
  upper_devicename: NM20AC1
  button_pin: GPIO0
  led_pin: GPIO2

esphome: !include ../base/name.yaml
esp32: !include ../esp32/nodemcu-32s.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
# Enable remote restart from HA
button: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_ledc.yaml
# Enable Bluetooth Low Energy
esp32_ble_tracker:
sensor: !include ../sensor/airtags.yaml

    