substitutions:
  devicename: sd01
  upper_devicename: SD01
  blue_led_pin: GPIO13
  min_value: '0'
  max_value: '90'
  gamma_correct: '0.0'

#external_components: !include ../external_components/sonoff_d1.yaml
esphome: !include ../base/name_onboot.yaml
esp8266: !include ../esp8266/esp8285_restore.yaml
wifi: !include ../connection/wifi.yaml
mqtt: !include ../connection/mqtt.yaml
# Enable logging
logger: !include ../logger/debug_no_uart.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota:
uart: !include ../uart/default_9600baud.yaml
button: !include ../button/restart.yaml
output: !include ../output/blue_led.yaml
light:
  - <<: !include ../light/blue_led.yaml
  - <<: !include ../light/sonoff_d1.yaml

