- platform: ld2410
  distance_resolution:
    name: "Distance Resolution"
#  baud_rate:
#    name: "Baud Rate"
#  light_function:
#    name: "Light Function"
#  out_pin_level:
#    name: "Out Pin Level"
