substitutions:
  devicename: dm08tph
  upper_devicename: DM08TPH
  device_friendly_name: "DM08TPH Climate"
  blue_led_pin: D4
  temp_offset: "-3.6" # Celsius

esphome: !include ../base/device_friendly_name_onboot.yaml
esp8266: !include ../esp8266/d1mini.yaml
wifi: !include ../connection/wifi_desert.yaml
mqtt: !include ../connection/mqtt_desert.yaml
# Enable logging
logger: !include ../logger/debug.yaml
# Expose some info to HA
text_sensor: !include ../text_sensor/wifi_info.yaml
ota: !include ../ota/esphome.yaml
# Enable remote restart from HA
button: !include ../button/restart.yaml
light: !include ../light/blue_led.yaml
output: !include ../output/blue_led.yaml
# Need I2C bus for sensors
i2c: !include ../connection/i2c.yaml
# BME280 Temperature, Pressure and Humidity
sensor: !include ../sensor/bme280_i2c.yaml

