- platform: template
  name: "${upper_devicename} Cover"
  optimistic: True
  open_action:
    - output.set_level:
        id: nodemcu_servo
        level: 50%
  close_action:
    - output.set_level:
        id: nodemcu_servo
        level: 0%
