- platform: mqtt_subscribe
  name: "${upper_devicename} Cover"
  id: mqtt_cover_tilt
  topic: "${devicename}/cover/${devicename}_cover/tilt/command"
  qos: 0
  discovery: False
  on_value:
    then:
      - logger.log:
          format: "Setting cover tilt commanded value"
          tag: "sensor.mqtt_subscribe.cover.tilt"
      - while:
          condition:
            lambda: |-
              return (int(x) != id(tilt_out));
          then:
            - lambda: |-
                if (int(x) > id(tilt_out)) {
                  id(tilt_out)++;
                } else if (int(x) < id(tilt_out)) {
                  id(tilt_out)--;
                }
            - delay: 100ms
            - output.set_level:
                id: nodemcu_servo
                level: !lambda |-
                  return id(tilt_out)/100.0f;
            - mqtt.publish:
                topic: "${devicename}/cover/${devicename}_cover/tilt/state"
                payload: !lambda "return to_string(id(tilt_out));"
                qos: 0
                retain: True
      - mqtt.publish:
          topic: "${devicename}/cover/${devicename}_cover/state"
          payload: !lambda |-
            if (x > 5) {
              return "open";
            } else {
              return "closed";
            }
          qos: 0
          retain: True
- platform: adc
  pin: A0
  name: "${upper_devicename} Cover Tilt Sensor"
  update_interval: 1s
  filters:
    - debounce: 0.5s
    - delta: 0.03
  on_value:
    then:
      - mqtt.publish:
          topic: "${devicename}/cover/${devicename}_cover/tilt/command"
          payload: !lambda "return to_string(int(x*100.0));"
          qos: 0
          retain: True
      - logger.log:
          format: "Setting cover tilt manual value"
          tag: "sensor.mqtt_subscribe.cover.tilt"
