- platform: template
  name: "${upper_devicename} Cover"
  id: ${devicename}
  mqtt_id: ${devicename}_cover
  device_class: shutter
  optimistic: False
  discovery: False
  lambda: |-
    if (int(id(${devicename}).tilt * 100) > 5) {
      return COVER_OPEN;
    } else {
      return COVER_CLOSED;
    }
  tilt_action:
    - while:
        condition:
          lambda: |-
            return (int(tilt*100) != id(tilt_out));
        then:
          - lambda: |-
              if (int(tilt*100) > id(tilt_out)) {
                id(tilt_out)++;
              } else if (int(tilt*100) < id(tilt_out)) {
                id(tilt_out)--;
              }
          - delay: 100ms
          - servo.write:
              id: cover_servo
              level: !lambda |-
                return id(tilt_out)/100.0f;
    - servo.detach: cover_servo
  tilt_lambda: |-
    return id(tilt_out)/100.0f;

