- platform: tilt
  name: "${upper_devicename} Cover"
  id: ${devicename}
  mqtt_id: ${devicename}_cover
  device_class: blind
  tilt_closed_value: 5%
  tilt_opened_value: 45%
  tilt_action:
    - output.set_level:
        id: nodemcu_servo
        level: !lambda |-
          return id(${devicename})->tilt;

