- platform: bang_bang
  name: "${upper_devicename} Hot Water Recirc Control"
  sensor: probe_${probe_number}
  default_target_temperature_low: 38째C
  default_target_temperature_high: 44째C
  visual:
    min_temperature: 20째C
    max_temperature: 50째C

  heat_action:
    - switch.turn_on: relay_${relay_number}
  idle_action:
    - switch.turn_off: relay_${relay_number}