- platform: bang_bang
  name: "${upper_devicename} Hot Water Recirc Control"
  sensor: probe_${probe_number}
  default_target_temperature_low: 32.222°C
  default_target_temperature_high: 43.333°C
  visual:
    min_temperature: 10.000°C
    max_temperature: 54.444°C
    
  away_config:
    default_target_temperature_low: 12.778°C
    default_target_temperature_high: 26.667°C

  heat_action:
    - switch.turn_on: relay_${relay_number}
  idle_action:
    - switch.turn_off: relay_${relay_number}