- platform: template
  name: "${upper_devicename} Cover"
  id: ${devicename}
  mqtt_id: ${devicename}_cover
  device_class: ${device_class}
  optimistic: False
  discovery: False
  lambda: |-
    if (${tilt_max} < ${tilt_min}) {
      if (id(tilt_out) < (100 - ${open_above_tilt})) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    } else {
      if (id(tilt_out) > ${open_above_tilt}) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    }
  tilt_action:
    - lambda: |-
        id(tilt_out) = int(tilt*100);
    - servo.write:
        id: cover_servo
        level: !lambda |-
          return id(tilt_out)/100.0f;
  tilt_lambda: |-
    return id(tilt_out)/100.0f;

