- platform: restart
  name: "${upper_devicename} Restart"
- platform: gpio
  name: "${devicename}_1"
  restore_mode: RESTORE_DEFAULT_OFF
  pin:
    number: 13
    inverted: yes
- platform: gpio
  name: "${devicename}_2"
  restore_mode: RESTORE_DEFAULT_OFF
  pin:
    number: 12
    inverted: yes
- platform: gpio
  name: "${devicename}_3"
  restore_mode: RESTORE_DEFAULT_OFF
  pin:
    number: 14
    inverted: yes
- platform: gpio
  name: "${devicename}_4"
  restore_mode: RESTORE_DEFAULT_OFF
  pin:
    number: 16
    inverted: yes

