- platform: adc
  pin: A0
  name: "Level Sensor"
  id: level_sensor
  unit_of_measurement: '%'
  accuracy_decimals: "${level_accuracy}"
  update_interval: ${update_interval}
  expire_after: 600s
  filters:
    - lambda: return ${level_offset} - x;
    - multiply: ${multiplier}
    - calibrate_linear:
        datapoints:
          - 4.5 -> 4.0
          - 12.9 -> 7.1
          - 16.0 -> 10.1
          - 26.6 -> 13.2
          - 27.5 -> 16.2
          - 29.7 -> 19.3
          - 31.7 -> 22.4
          - 32.7 -> 25.5
          - 35.5 -> 28.6
          - 37.5 -> 31.7
          - 38.5 -> 34.7
          - 40.9 -> 37.8
          - 42.1 -> 40.9
          - 45.4 -> 44.0
          - 49.2 -> 50.2
          - 50.5 -> 53.2
          - 53.3 -> 56.3
          - 54.7 -> 59.4
          - 57.6 -> 62.5
          - 60.8 -> 65.5
          - 62.4 -> 68.6
          - 65.5 -> 71.7
          - 67.1 -> 74.8
          - 69.8 -> 77.9
          - 74.9 -> 81.0
          - 79.7 -> 84.1
          - 82.1 -> 87.2
          - 87.7 -> 90.2
          - 90.4 -> 93.3
          - 96.7 -> 96.5
          - 99.8 -> 100.0        
    - sliding_window_moving_average:
        window_size: "${window_size}"
        send_every: "${send_every}"
