- platform: adc
  pin: A0
  name: "Pressure Sensor"
  unit_of_measurement: psi
  accuracy_decimals: 0
  device_class: pressure
  update_interval: ${update_interval}
  expire_after: 600s
  filters:
    - offset: ${offset}
    - multiply: ${multiplier}
    - sliding_window_moving_average:
        window_size: "${window_size}"
        send_every: "${send_every}"