- platform: adc
  pin: A0
  name: "${upper_devicename} Light Sensor"
  update_interval: 10s
  expire_after: 60s
  filters:
    - median:
        window_size: 7
        send_every: 3
        send_first_at: 1