- platform: adc
  pin: A0
  name: "${upper_devicename} Cover Tilt Sensor"
  update_interval: 1s
  expire_after: 60s
  filters:
    - delta: 0.05
  on_value:
    then:
      - cover.control:
          id: ${devicename}
          tilt: !lambda "return x;"
      - logger.log:
          format: "Setting cover tilt manual value"
          tag: "sensor.cover.tilt"
