- platform: adc
  pin: A0
  name: "Pressure Sensor"
  id: pressure_sensor
  unit_of_measurement: psi
  accuracy_decimals: "${pressure_accuracy}"
  device_class: pressure
  update_interval: ${update_interval}
  expire_after: 600s
  filters:
    - lambda: return x + id(pressure_offset);
    - multiply: ${multiplier}
    - sliding_window_moving_average:
        window_size: "${window_size}"
        send_every: "${send_every}"