- platform: bme280
  temperature:
    name: "${upper_devicename} Temperature"
    oversampling: 16x
    unit_of_measurement: "°C"
    device_class: temperature
    icon: mdi:thermometer
    accuracy_decimals: 1
    expire_after: 600s
    filters:
      - or:
        - delta: 0.5
        - heartbeat: 300s
  pressure:
    name: "${upper_devicename} Pressure"
    oversampling: 16x
    unit_of_measurement: "hPa"
    device_class: pressure
    icon: mdi:gauge
    accuracy_decimals: 1
    expire_after: 600s
    filters:
      - or:
        - delta: 1
        - heartbeat: 300s
  humidity:
    name: "${upper_devicename} Humidity"
    oversampling: 16x
    unit_of_measurement: "%"
    device_class: humidity
    icon: mdi:water-percent
    accuracy_decimals: 1
    expire_after: 600s
    filters:
      - or:
        - delta: 0.5
        - heartbeat: 300s
  address: 0x77
  update_interval: 10s
