- platform: bme280_i2c
  temperature:
    name: "Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    icon: mdi:thermometer
    accuracy_decimals: 1
    oversampling: 1x
    expire_after: 600s
    filters:
      - or:
        - delta: 0.5
        - heartbeat: 300s
        - offset: "${temp_offset}"
  pressure:
    name: "Pressure"
    unit_of_measurement: "hPa"
    device_class: pressure
    icon: mdi:gauge
    accuracy_decimals: 1
    oversampling: 1x
    expire_after: 600s
    filters:
      - or:
        - delta: 1
        - heartbeat: 300s
  humidity:
    name: "Humidity"
    unit_of_measurement: "%"
    device_class: humidity
    icon: mdi:water-percent
    accuracy_decimals: 1
    oversampling: 1x
    expire_after: 600s
    filters:
      - or:
        - delta: 0.5
        - heartbeat: 300s
  address: 0x77
  update_interval: 60s
