- platform: bmp280
  temperature:
    name: "${upper_devicename} Temperature"
    oversampling: 16x
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    expire_after: 600s
    filters:
      - or:
        - delta: 0.5
        - heartbeat: 300s
  pressure:
    name: "${upper_devicename} Pressure"
    oversampling: 16x
    unit_of_measurement: "hPa"
    accuracy_decimals: 1
    expire_after: 600s
    filters:
      - or:
        - delta: 1
        - heartbeat: 300s
  address: 0x77
  update_interval: 10s
