- platform: dallas
  id: "probe_1"
  address: ${probe_1_addr}
  name: "${upper_devicename} ${probe_1_addr}"
  unit_of_measurement: °C
  icon: mdi:thermometer
  device_class: temperature
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.5
        - heartbeat: 300s
