- platform: dallas
  address: 0xDC000008E3B1AB28
  name: "Temperature Probe 1"
  unit_of_measurement: "ºC"
  icon: mdi:thermometer
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.1
        - heartbeat: 300s
- platform: dallas
  address: 0xDE000008E2B6AF28
  name: "Temperature Probe 2"
  unit_of_measurement: "ºC"
  icon: mdi:thermometer
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.1
        - heartbeat: 300s
- platform: dallas
  address: 0xC400000A01299728
  name: "Temperature Probe 3"
  unit_of_measurement: "ºC"
  icon: mdi:thermometer
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.1
        - heartbeat: 300s
- platform: dallas
  address: 0x7B00000A00BBB128
  name: "Temperature Probe 4"
  unit_of_measurement: "ºC"
  icon: mdi:thermometer
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.1
        - heartbeat: 300s
