- platform: one_wire
  address: ${probe_3_addr}
  id: "probe_3"
  name: "Temperature Probe 3"
  unit_of_measurement: "°C"
  device_class: temperature
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.5
        - heartbeat: 300s
