- platform: dallas
  address: ${probe_1_addr}
  name: "${upper_devicename} ${probe_1_addr}"
  unit_of_measurement: "ºC"
  device_class: temperature
  icon: mdi:thermometer
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.5
        - heartbeat: 300s
- platform: dallas
  address: ${probe_2_addr}
  name: "${upper_devicename} ${probe_2_addr}"
  unit_of_measurement: "ºC"
  device_class: temperature
  icon: mdi:thermometer
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.5
        - heartbeat: 300s
- platform: dallas
  address: ${probe_3_addr}
  name: "${upper_devicename} ${probe_3_addr}"
  unit_of_measurement: "ºC"
  device_class: temperature
  icon: mdi:thermometer
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.5
        - heartbeat: 300s
- platform: dallas
  address: ${probe_4_addr}
  name: "${upper_devicename} ${probe_4_addr}"
  unit_of_measurement: "ºC"
  device_class: temperature
  icon: mdi:thermometer
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.5
        - heartbeat: 300s
