- platform: dallas_temp
  address: ${probe_4_addr}
  id: "probe_4"
  name: "Temperature Probe 4"
  unit_of_measurement: "°C"
  device_class: temperature
  accuracy_decimals: 1
  update_interval: ${update_interval}
  expire_after: 600s
  filters:
    - or:
        - delta: 0.5
        - heartbeat: 300s
