- platform: dallas
  address: 0x28ABB1E3080000DC
  name: "Temperature Probe 1"
  unit_of_measurement: "ºC"
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.1
        - heartbeat: 300s
- platform: dallas
  address: 0x28AFB6E2080000DE
  name: "Temperature Probe 2"
  unit_of_measurement: "ºC"
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.1
        - heartbeat: 300s
- platform: dallas
  address: 0x289729010A0000C4
  name: "Temperature Probe 3"
  unit_of_measurement: "ºC"
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.1
        - heartbeat: 300s
- platform: dallas
  address: 0x28B1BB000A00007B
  name: "Temperature Probe 4"
  unit_of_measurement: "ºC"
  accuracy_decimals: 1
  expire_after: 600s
  filters:
    - or:
        - delta: 0.1
        - heartbeat: 300s

