- platform: modbus_controller
  modbus_controller_id: epever
  id: charging_power
  name: "Charging Power"
  address: 0x3106
  unit_of_measurement: "W"
  register_type: read
  value_type: U_DWORD_R
  accuracy_decimals: 1
  state_class: measurement
  device_class: power
  expire_after: ${expire_after}
  filters:
    - multiply: 0.01
    - clamp:
        max_value: 7200.0 # Max rated
        min_value: 0.0
        ignore_out_of_range: true
