- platform: modbus_controller
  modbus_controller_id: epever
  id: power_components_temperature
  name: "${upper_devicename} Power Components Temperature"
  address: 0x3112
  unit_of_measurement: °C
  register_type: read
  value_type: S_WORD
  accuracy_decimals: 1
  filters:
    - multiply: 0.01


