- platform: modbus_controller
  modbus_controller_id: epever
  id: charging_voltage
  name: "Charging Voltage"
  address: 0x3104
  unit_of_measurement: "V"
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  state_class: measurement
  device_class: voltage
  filters:
    - multiply: 0.01
    - lambda: !lambda |-
        if (0 >= x > 40) return {};
        return x;
