- platform: modbus_controller
  modbus_controller_id: epever
  id: battery_status
  name: "Battery Status"
  address: 0x3200
  register_type: read
  value_type: U_WORD
  bitmask: 7  #(Bits 0-3)
  accuracy_decimals: 0
