- platform: modbus_controller
  modbus_controller_id: epever
  id: charging_power
  name: "Charging Power"
  address: 0x3106
  unit_of_measurement: "W"
  register_type: read
  value_type: U_DWORD_R
  accuracy_decimals: 1
  state_class: measurement
  device_class: power
  filters:
    - multiply: 0.01
    - lambda: !lambda |-
        if (x > (60*120)) return {};
        return x;
