- platform: modbus_controller
  modbus_controller_id: epever
  id: battery_current
  name: "Battery Current"
  address: 0x331B
  register_type: read
  value_type: S_DWORD_R
  register_count: 2
  accuracy_decimals: 2
  unit_of_measurement: "A"
  state_class: measurement
  device_class: current
  expire_after: ${expire_after}
  filters:
    - multiply: 0.01
    - clamp:
        max_value: 60.0 # Max rated
        min_value: 0.0
        ignore_out_of_range: true
