- platform: modbus_controller
  modbus_controller_id: epever
  id: charger_status
  name: "Charger Status"
  address: 0x3201
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 0
  expire_after: ${expire_after}
