- platform: modbus_controller
  modbus_controller_id: epever
  id: charging_mode
  name: "${upper_devicename} Charging Mode"
  address: 0x3008
  unit_of_measurement: ""
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 0
