- platform: modbus_controller
  modbus_controller_id: epever
  id: array_rated_current
  name: "${upper_devicename} Array Rated Current"
  address: 0x3001
  unit_of_measurement: "A"
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 2
  filters:
    - multiply: 0.01
