- platform: modbus_controller
  modbus_controller_id: epever
  id: charging_current
  name: "Charging Current"
  address: 0x3105
  unit_of_measurement: "A"
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  state_class: measurement
  device_class: current
  filters:
    - multiply: 0.01
    - lambda: !lambda |-
        if (x > 60) return {};
        return x;
