- platform: modbus_controller
  modbus_controller_id: epever
  id: charging_voltage
  name: "${upper_devicename} Charging Voltage"
  address: 0x3104
  unit_of_measurement: "V"
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
    - multiply: 0.01
