- platform: modbus_controller
  modbus_controller_id: epever
  id: array_rated_voltage
  name: "${upper_devicename} Array Rated Voltage"
  address: 0x3000
  unit_of_measurement: "V"
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
    - multiply: 0.01
