- platform: modbus_controller
  modbus_controller_id: epever
  id: charging_current
  name: "${upper_devicename} Charging Current"
  address: 0x3105
  unit_of_measurement: "A"
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
    - multiply: 0.01
