- platform: modbus_controller
  modbus_controller_id: epever
  id: array_rated_power
  name: "Array Rated Power"
  address: 0x3002
  unit_of_measurement: "W"
  register_type: read
  value_type: U_DWORD_R
  accuracy_decimals: 1
  filters:
    - multiply: 0.01
