- platform: modbus_controller
  modbus_controller_id: epever
  id: generated_energy_today
  name: "${upper_devicename} Generated Energy Today"
  address: 0x330C
  register_type: read
  value_type: U_DWORD_R
  accuracy_decimals: 0
  unit_of_measurement: "Wh"
  filters:
    - multiply: 10.0
