- platform: modbus_controller
  modbus_controller_id: epever
  id: array_input_current
  name: "${upper_devicename} Array Input Current"
  address: 0x3101
  unit_of_measurement: "A" ## for any other unit the value is returned in minutes
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 2
  filters:
    - multiply: 0.01


