- platform: modbus_controller
  modbus_controller_id: epever
  id: battery_voltage
  name: "Battery Voltage"
  address: 0x331A
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  unit_of_measurement: "V"
  state_class: measurement
  device_class: voltage
  expire_after: ${expire_after}
  filters:
    - multiply: 0.01
    - clamp:
        max_value: 40.0 # Max rated
        min_value: 0.0
        ignore_out_of_range: true
