- platform: modbus_controller
  modbus_controller_id: epever
  id: max_battery_voltage_today
  name: "${upper_devicename} Maximum Battery Voltage Today"
  address: 0x3302
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  unit_of_measurement: "V"
  filters:
    - multiply: 0.01
