- platform: modbus_controller
  modbus_controller_id: epever
  id: charger_status
  name: "${upper_devicename} Charger Status"
  address: 0x3201
  register_type: read
  value_type: U_WORD
  bitmask: 0x00C0  #(Bits 3-4)
  accuracy_decimals: 0
