- platform: modbus_controller
  modbus_controller_id: epever
  id: array_input_voltage
  name: "Array Input Voltage"
  address: 0x3100
  unit_of_measurement: "V" ## for any other unit the value is returned in minutes
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  state_class: measurement
  device_class: voltage
  filters:
    - multiply: 0.01
    - lambda: !lambda |-
        if ((0 > x) || (x > 120)) return {};
        return x;
