- platform: modbus_controller
  modbus_controller_id: epever
  id: min_battery_today
  name: "Minimum Battery Voltage Today"
  address: 0x3303
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  unit_of_measurement: "V"
  state_class: measurement
  device_class: voltage
  skip_updates: ${skip_updates}
  filters:
    - multiply: 0.01
    - lambda: !lambda |-
        if (x > 40) return {};
        return x;
