- platform: modbus_controller
  modbus_controller_id: epever
  id: array_input_power
  name: "Array Input Power"
  address: 0x3102
  unit_of_measurement: "W" ## for any other unit the value is returned in minutes
  register_type: read
  value_type: U_DWORD_R
  accuracy_decimals: 1
  state_class: measurement
  device_class: power
  expire_after: ${expire_after}
  filters:
    - multiply: 0.01
    - clamp:
        max_value: 7200.0 # 60x120
        min_value: 0.0
        ignore_out_of_range: true
