- platform: modbus_controller
  modbus_controller_id: epever
  id: max_pv_voltage_today
  name: "Maximum PV Voltage Today"
  address: 0x3300
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  unit_of_measurement: "V"
  state_class: measurement
  device_class: voltage
  skip_updates: ${skip_updates}
  filters:
    - multiply: 0.01
    - lambda: !lambda |-
        if (x > 120) return {};
        return x;
