- platform: modbus_controller
  modbus_controller_id: epever
  id: power_components_temperature
  name: "Power Components Temperature"
  address: 0x3112
  unit_of_measurement: °C
  register_type: read
  value_type: S_WORD
  accuracy_decimals: 1
  state_class: measurement
  device_class: temperature
  expire_after: ${expire_after}
  filters:
    - multiply: 0.01
    - clamp:
        max_value: 100.0 # Max rated
        min_value: -40.0
        ignore_out_of_range: true


