- platform: modbus_controller
  modbus_controller_id: epever
  id: battery_voltage
  name: "${upper_devicename} Battery Voltage"
  address: 0x331A
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  unit_of_measurement: "V"
  filters:
    - multiply: 0.01
