- platform: modbus_controller
  modbus_controller_id: epever
  id: battery_voltage
  name: "Battery Voltage"
  address: 0x331A
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  unit_of_measurement: "V"
  state_class: measurement
  device_class: voltage
  filters:
    - multiply: 0.01
    - lambda: !lambda |-
        if (x > 40) return {};
        return x;
