- platform: modbus_controller
  modbus_controller_id: epever
  id: generated_energy_today
  name: "Generated Energy Today"
  address: 0x330C
  register_type: read
  value_type: U_DWORD_R
  accuracy_decimals: 0
  unit_of_measurement: "Wh"
  state_class: total_increasing
  device_class: energy
  skip_updates: ${skip_updates}
  expire_after: ${expire_after}
  filters:
    - multiply: 10.0
    - clamp:
        max_value: 5760.0 # 40x12x12
        min_value: 0.0
        ignore_out_of_range: true
