- platform: modbus_controller
  modbus_controller_id: epever
  id: battery_rated_current
  name: "${upper_devicename} Battery Rated Current"
  address: 0x3005
  unit_of_measurement: "A"
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  filters:
    - multiply: 0.01

