- platform: ina219
  address: 0x40
  shunt_resistance: ${shunt_resistance}
  current:
    name: "Current"
  power:
    name: "Power"
  bus_voltage:
    name: "Bus Voltage"
  shunt_voltage:
    name: "Shunt Voltage"
  max_voltage: ${max_voltage}
  max_current: ${max_current}
  update_interval: ${update_interval}