- platform: qmc5883l
  field_strength_x:
    name: "Field Strength X"
    filters:
      throttle: ${x_throttle}
#   field_strength_y:
#     name: "Field Strength Y"
  field_strength_z:
    id: field_strength_z
    internal: true
    filters:
      delta: ${delta}
#    name: "Field Strength Z"
#   heading:
#     name: "Heading"
  range: 200uT
  oversampling: ${oversampling}
  update_interval: "${update_interval}"
