- platform: qmc5883l
  field_strength_x:
    name: "Field Strength X"
  field_strength_y:
    name: "Field Strength Y"
  field_strength_z:
    name: "Field Strength Z"
  heading:
    name: "Heading"
  range: 200uT
  oversampling: 512x
  update_interval: 60s