- platform: rotary_encoder
  name: "${upper_devicename} Rotary Encoder"
  id: encoder
  pin_a:
    number: ${encoder_pin_a}
    mode: INPUT_PULLUP
  pin_b:
    number: ${encoder_pin_b}
    mode: INPUT_PULLUP
  min_value: ${encoder_min_value}
  max_value: ${encoder_max_value}
- platform: mqtt_subscribe
  name: "${upper_devicename} Set Rotary Encoder"
  topic: ${set_rotary_encoder_topic}
  accuracy_decimals: 0
  on_value:
    then:
      - sensor.rotary_encoder.set_value:
          id: encoder
          value: !lambda |-
            return x;
