- platform: rotary_encoder
  name: "${upper_devicename} Rotary Encoder"
  id: encoder
  pin_a:
    number: ${encoder_pin_a}
    mode: INPUT_PULLUP
  pin_b:
    number: ${encoder_pin_b}
    mode: INPUT_PULLUP
  min_value: ${encoder_min_value}
  max_value: ${encoder_max_value}
  on_value:
    then:
      - mqtt.publish:
          topic: ${rotary_encoder_out_topic}
          payload: !lambda |-
            char result[5];
            dtostrf(id(encoder).state,1,0,result);
            return result;
- platform: mqtt_subscribe
  name: "${upper_devicename} Set Rotary Encoder"
  topic: ${set_rotary_encoder_topic}
  accuracy_decimals: 0
  filters:
    - delta: 1.0
  on_value:
    then:
      - sensor.rotary_encoder.set_value:
          id: encoder
          value: !lambda |-
            return x;
