- platform: sht4x
  temperature:
    name: "${upper_devicename} Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    icon: mdi:thermometer
    accuracy_decimals: 1
    expire_after: 600s
    filters:
      - or:
        - delta: 0.5
        - heartbeat: 300s
  humidity:
    name: "${upper_devicename} Humidity"
    unit_of_measurement: "%"
    device_class: humidity
    icon: mdi:water-percent
    accuracy_decimals: 1
    expire_after: 600s
    filters:
      - or:
        - delta: 0.5
        - heartbeat: 300s
  address: 0x44
  update_interval: 10s


