- platform: template
  name: "None"
  id: ${lock_id}
  optimistic: true
  retain: true
  unlock_action:
    - servo.write:
        id: ${servo_id}
        level: ${on_level}
  lock_action:
    - servo.write:
        id: ${servo_id}
        level: ${off_level}
